### ISSUE TITLE
Aggiungere la documentazione sui siti di test disponibili

### ISSUE THREAD

**Issue by ncarandini** [italia/spid-regole-tecniche#14]
Sarebbe utile scrivere un paio di pagine di documentazione sui servizi IdP di test disponibili:
- Poste.it
- Docker container col servizio di riferimento

Se siete d'accordo io posso scrivere quello per l'uso del servizio di test di Poste.it, visto che è quello che uso quotidianamente nello sviluppo dell'SDK per .NET.

**Comment by alexrj** [comment]
Concordo sulla necessità di documentare questi aspetti ma credo che sia opportuno inserirli in una guida a parte, più discorsiva. Ci lavoreremo presto.
Questo repository contiene le regole tecniche, quindi un documento di specifiche con valore normativo.

**Comment by ncarandini** [comment]
Allora aprite un altro repository e fateci contribuire... :-)

**Comment by peppelinux** [comment]
ciao @ncarandini,
attualmente accettiamo PR sul branch master e pubblichiamo solo ad avvenuta release. Sarò felice di accogliere tutti i contributi che riterrai opportuno dare a questo progetto, perdona tanto il ritardo nelle risposte ma eccoci qui, pronti a ripartire!
