### ISSUE TITLE
Allineamento con regole tecniche PDF e avvisi

### ISSUE THREAD

**Issue by alranel** [italia/spid-regole-tecniche#16]
Questo documento presenta diversi disallineamenti con le regole tecniche pubblicate in PDF e con i relativi avvisi che le vanno ad emendare. Tra questi:

* campi obbligatori nei metadati dei Service Provider (https://github.com/italia/spid-testenv/issues/17)

**Comment by peppelinux** [comment]
done
https://github.com/italia/spid-regole-tecniche/pull/37
