### ISSUE TITLE
Binding SOAP per Identity Provider

### ISSUE THREAD

**Issue by alranel** [italia/spid-regole-tecniche#18]
Premetto che potrei essere io a non capire, quindi è più una richiesta di chiarimento che una segnalazione.

Nell'[avviso n. 3](http://www.agid.gov.it/sites/default/files/documentazione/spid-avviso-n3-chiarimenti-sessioni-singlelogout.pdf) (paragrafo 2.3.1) si dice:

> La richiesta di single logout, quando operata dall’utente presso un fornitore di servizi, **deve comunque essere iniziata utilizzando uno dei binding asincroni** resi disponibili dai gestori dell’identità, per dar modo ai gestori dell’identità di completare il processo anche presso i fornitori di servizi sprovvisti di interfacce SOAP. Per rafforzare tale prescrizione i gestori dell’identità, _pur dovendo essere in grado di supportare il binding SOAP_, **non dovranno pubblicare interfacce richiesta di single logout secondo tale modalità**.

Immagino che la frase _"pur dovendo essere in grado di supportare il binding SOAP"_ vada interpretata solo limitatamente alle chiamate SOAP in uscita verso i Service Provider, e non a quelle in entrata.

Tuttavia se l'avviso proibisce agli Identity Provider di pubblicare interfacce SOAP non capisco perché nel successivo paragrafo 2.4 dello stesso documento si riporta anche SOAP tra i possibili binding nei metadati di un Identity Provider:

> * il formato dei metadata del gestore dell’identità deve prevedere la presenza nell’elemento `<IDPSSODescriptor>` di uno o più elementi `<SingleLogoutService>` che specificano l’indirizzo del Single Logout Service riportanti i seguenti attributi:
>   * `Location` url endpoint del servizio per la ricezione delle richieste di Single Logout;
>   * `Binding` che può assumere uno dei valori:
>     * "`urn:oasis:names:tc:SAML:2.0:bindings::SOAP`
>     * “`urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect`"
>     * "`urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST`";

**Comment by peppelinux** [comment]
Risolto e con l'occasione ho trovato altre inesattezze che ho disambiguato alla meno peggio.
Purtroppo si trovano troppo spesso delle definizioni un po "enigmistiche"

**Comment by peppelinux** [comment]
https://github.com/italia/spid-regole-tecniche/commit/1dd4757b11196366a45e9a2cd66dad1c14a9f91a
