### ISSUE TITLE
Spostare qui il file XSD dei metadata?

### ISSUE THREAD

**Issue by alranel** [italia/spid-regole-tecniche#19]
Suggerisco di spostare in questo repository il file XSD dei metadata dei Service Provider pubblicato in https://github.com/italia/spid-metadata-builder/blob/master/saml-schema-metadata-SPID-SP.xsd dal momento che una volta pubblicato dovrebbe seguire di pari passo l'aggiornamento delle Regole Tecniche che riflette.

Discussione sul forum: https://forum.italia.it/t/sp-metadata-xsd/1879/2

**Comment by peppelinux** [comment]
Ecco due esempi pythonici per la costruzione automatica dei metadata
https://github.com/italia/Satosa-Saml2Spid/blob/4226a49e65a0bc4904d240f39e969e7c1a4329be/example/backends/spidsaml2.py#L29

https://github.com/peppelinux/djangosaml2_spid/blob/02bcfec07dad7fbc14025ae1ebe4675ee59bcdfd/src/djangosaml2_spid/views.py#L317

su spid-metadata-builder ... Credo che daremo una svecchiata anche li. Tempo al tempo

**Comment by peppelinux** [comment]
Attualmente gli xsd utilizzati da AgID per i test di accreditamento sono qui pubblicati:
https://github.com/italia/spid-saml-check/tree/master/specs-compliance-tests/xsd

**Comment by peppelinux** [comment]
Consideriamo gli xsd disponibili presso i repository dei validatori ufficiali SPID.

a breve spid-saml-check e spid-testenv2 adotteranno spid-sp-test alla base, "a breve" vorrebbe indicare tra meno di un mese ...!
Ad oggi spid-sp-test risolve numerosi bug dei precedenti validatori e aggiunge ulteriori controlli in conformità alle regole tecniche e agli avvisi, 

https://github.com/italia/spid-sp-test/tree/main/src/spid_sp_test/xsd
