### ISSUE TITLE
Valore dell'attributo Destination

### ISSUE THREAD

**Issue by alranel** [italia/spid-regole-tecniche#20]
Mi sembra che ci sia un'incoerenza tra quanto prescritto dalle Regole Tecniche SPID e dalle specifiche SAML OASIS in merito all'attributo `Destination`.

Nelle [Regole Tecniche SPID](http://www.agid.gov.it/sites/default/files/circolari/spid-regole_tecniche_v1.pdf) è riportato quanto segue:

> * nell’ elemento `<AuthnRequest>` devono essere presenti i seguenti attributi:
>    * l’attributo `Destination`, a indicare l’indirizzo (URI reference) dell’Identity provider a cui è inviata la richiesta, come risultante nell’attributo **entityID** presente nel metadata IdP dell’Identity Provider a cui viene inviata la richiesta;

(Analoga indicazione è riportata per `Response` e `AttributeQuery`.)

Nelle specifiche [SAML OASIS](https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf) (righe 661-664 e poi 843-846) è riportato quanto segue a proposito dei binding HTTP-Redirect e HTTP-POST:

> If the message is signed, the `Destination` XML attribute in the root SAML element of the protocol message MUST contain the **URL** to which the sender has instructed the user agent to deliver the message. The recipient MUST then verify that the value matches the location at which the message has been received.

Ricapitolando:

* le Regole Tecniche SPID prescrivono l'uso dell'entityID della parte ricevente;
* le specifiche SAML OASIS prescrivono l'uso dell'URL del binding stesso.

Anche l'IdP di test segue le specifiche SAML OASIS, di fatto forzando gli sviluppatori ad ignorare la verifica di sicurezza prescritta ("MUST"):

```
Destination validation for Authentication Request failed. Received: [spid-testenv-identityserver]. Expected one in the list: [https://spid-testenv-identityserver:9443/samlsso]
```

**Comment by alranel** [comment]
Questo problema è stato risolto dall'avviso 11:
https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n11-regolamento_recante_le_regole_tecniche-_specifica_saml-attributo_destination.pdf

**Comment by mauromol** [comment]
Buongiorno,
mi sembra di capire, dall'avviso 11 (https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n11-regolamento_recante_le_regole_tecniche-_specifica_saml-attributo_destination.pdf), che gli Identity Provider debbano supportare entrambi i tipi di `Destination`. Perché però allora le regole tecniche consolidate pubblicate su https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/single-sign-on.html tuttora prescrivono l'uso dell'entityID, sottolineando anzi che "il valore richiesto per l’attributo `Destination` differisce da quanto previsto dalle specifiche SAML"?
Personalmente preferirei di gran lunga seguire la specifica SAML (anche per non dover mettere mano alle librerie che, giustamente, seguono tale specifica), per cui mi sto chiedendo se, ad oggi, nell'implementare un SP SPID si può seguire questa strada o se ancora occorre deviare dalla specifica SAML, nonostante quanto previsto dall'avviso 11.
Grazie.

**Comment by peppelinux** [comment]
Ciao @mauromol 
prego di consultare l'ultima versione:
https://docs.italia.it/italia/spid/spid-regole-tecniche/it/34.1.1/index.html

**Comment by mauromol** [comment]
Grazie @peppelinux , ma i dubbi rimangono. 
Primo dubbio: quest'ultima versione è la 34.1.1, indicata come alternativa alla "stabile": mi chiedo quindi se sia una "work-in-progress", un "to-be" o se sia già normativa (nel qual caso però mi chiedo perché non sia "stabile").
In secondo luogo, non chiarisce il dubbio di cui sopra: questa nuova versione è un po' più verbosa e dice:

> Il valore richiesto per l’attributo `Destination` differisce da quanto previsto dalle specifiche [SAML Core 2.0](https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf) pagina 36. Come reso esplicito da [Avviso AgID numero 11](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n11-regolamento_recante_le_regole_tecniche-_specifica_saml-attributo_destination.pdf)

L'avviso numero 11 però, dopo aver preso atto della differenza, dice:

> Per limitare l'impatto del conflitto sulle implementazioni, si richiede agli identity provider SPID di supportare l’attributo *Destination* come descritto in entrambe le definizioni.

Quindi, l'avviso dice che gli IdP devono accettare entrambe le forme di `Destination`, mentre le regole tecniche, anche nell'ultima versione, si limitano a dire che va usato l'entityID, pur costituendo questa una difformità rispetto a quanto prescritto dallo standard SAML.

Pertanto ritorna la domanda: ad oggi, 2021, nell'implementare un SP si può seguire quanto previsto da SAML e vivere tranquilli, o bisogna comunque deviare dallo standard e seguire i dettami delle regole tecniche?

**Comment by peppelinux** [comment]
Ciao @mauromol
ottima osservazione, purtroppo SPID è un SAML2 "ristretto" a delle specifiche tecniche periodicamente integrate sotto forma di avviso.

Riguardo Docs ita la versione ufficiale è la 34.1.1, che sta ad indicare di essere allineata all'ultimo avviso ovvero il n34.
E' in corso per puntare "stabile" su questa versione.

Per quanto riguarda i tuoi dubbi posso dire che il valore Destination è abbastanza "SAML2" tale da considerare quanto indicato nell'avviso 11. Provvederò a correggere la docs

grazie, mi hai dato un importante riferimento. Lascio questa issue aperta fino a quando non correggerò la doc.
A presto e sentiti libero di fare opportune PR alla documentazione ufficiale, sarei veramente lieto di offrirti la mia modestissima revisione

**Comment by peppelinux** [comment]
Sarebbe decisamente migliorativo ottenere nelle Specifiche SPID il valore Destination aderente alle specifiche SAML2-Core.
Questo aspetto produce un grande impatto nell'utilizzo delle librerie SAML2, queste spesso necessitano di patch, quindi di essere forkate per "sostenere" questa specifica di SPID.

**Comment by peppelinux** [comment]
@mauromol Aggiungiamo che Destination attribute è opzionale stando a SAML2 core specs:

    Destination [Optional]
    A URI reference indicating the address to which this request has been sent. This is useful to prevent
    malicious forwarding of requests to unintended recipients, a protection that is required by some
    protocol bindings. If it is present, the actual recipient MUST check that the URI reference identifies
    the location at which the message was received. If it does not, the request MUST be discarded.
    Some protocol bindings may require the use of this attribute (see [SAMLBind]).

questo aspetto non viene "toccato" da [Saml2Int](https://kantarainitiative.github.io/SAMLprofiles/saml2int.html) il che conferma quanto stabilito da SAML2 core.

**Comment by mauromol** [comment]
Sì, però attenzione Giuseppe, perché dice: 

> Some protocol bindings may require the use of this attribute

Il document SAML2 Binding in effetti per entrambi HTTP Redirect (paragrafo 3.4.5.2) ed HTTP Post (3.5.5.2), che sono quelli usati in SPID, dice:

>The presence of the user agent intermediary means that the requester and responder cannot rely on the
transport layer for end-end authentication, integrity and confidentiality. URL-encoded messages MAY be
signed to provide origin authentication and integrity if the encoding method specifies a means for signing.

oppure:

>The presence of the user agent intermediary means that the requester and responder cannot rely on the
transport layer for end-end authentication, integrity or confidentiality protection and must authenticate the
messages received instead. SAML provides for a signature on protocol messages for authentication and
integrity for such cases. Form-encoded messages MAY be signed before the base64 encoding is applied

Di conseguenza, in entrambi i casi:

>If the message is signed, the Destination XML attribute in the root SAML element of the protocol
message MUST contain the URL to which the sender has instructed the user agent to deliver the
message. The recipient MUST then verify that the value matches the location at which the message has
been received.

Sono entrambi dei MUST, quindi direi che questi sono casi in cui il binding impone l'uso della `Destination`, proprio per quanto detto prima, e cioè che, vista l'intermediazione del browser dell'utente, in questo caso non è possibile affidarsi al protocollo di trasporto per avere la certezza su chi sia il destinatario ultimo del messaggio.

**Comment by peppelinux** [comment]
È vero, destination è must solo nelle operazioni async mediate dallo user agent

**Comment by peppelinux** [comment]
@mauromol sentiti libero di fare la tua revisione su questo
https://github.com/italia/spid-regole-tecniche/pull/49

potremmo considerare questa issue prossima alla conclusione :)
Domattina unirò su master e farò release così da averla su Docs Italia
