### ISSUE TITLE
Chiarimento frase su processamento della Response

### ISSUE THREAD

**Issue by alranel** [italia/spid-regole-tecniche#21]
Nel paragrafo 1.3.1 (*Regole di processamento della `<Response>`), che indica i controlli che un SP deve fare alla ricezione di una Response prima di utilizzarne l'asserzione, è riportato questo passaggio:

> Il fornitore di servizi deve garantire che le asserzioni non vengano ripresentate, mantenendo il set di identificatori di richiesta (ID) usati come per le <AuthnRequest> per tutta la durata di tempo per cui l'asserzione risulta esser valida in base dell’attributo NotOnOrAfter dell’elemento <SubjectConfirmationData> presente nell’asserzione stessa.

Il significato di questa frase non mi è molto chiaro. Alcune possibili interpretazioni:

1. Se ricevo una Response che ha lo stesso ID di un'altra response che si trova ancora nella sua finestra di `NotOnOrAfter`, devo ignorarla.
2. Se ricevo una Response che ha lo stesso `InResponseTo` di un'altra asserzione già vista (e che si trova ancora nella sua finestra di `NotOnOrAfter`) ma ID differente, devo ignorarla.

La prima interpretazione di fatto suggerisce ai SP di tenere traccia in un database di tutti gli ID delle risposte ricevute, con i relativi valori di scadenza (`NotOnOrAfter`), ma non riesco ad immaginare uno scenario di attacco che questo check possa prevenire, perché mi basterebbe creare un nuovo ID e -al netto di tutti gli altri check- questa seconda asserzione verrebbe accettata.

La seconda interpretazione suggerisce invece che ad ogni AuthnRequest può seguire una ed una sola Response (anche eventualmente ripresentata più volte) ma qualsiasi ulteriore response con ID differente dalla prima va ignorata. Anche qui non immagino uno scenario di attacco.

Oggi @umbros mi diceva che la seconda è quella corretta. Suggerisco di chiarire questo passaggio in una futura revisione delle regole per assicurarsi che gli sviluppatori implementino il check corretto. :)

**Comment by peppelinux** [comment]
Response con ID differenti da quelli originari vengono accettati da un SP esclusivamente se questo consente la ricezione di "unsolicited responses". Di fatto questo non dovrebbe mai avvenire, fatta eccezioni di alcuni casi in cui il modello di distribuzione e bilanciamento di un SP presenti evidenti limiti di storage degli stati e delle "outstanding queries". 

un esempio è quello dell'adozione dei proxy, anche se questi consentissero di ricevere le unsolicited responses di fatto poi gli SP farebbero fallire l'esito dell'HTTP POST.

Questo è un ambito generico delle specifiche OASIS SAML2 e di tutte le librerie che le adottano, queste già adottano un comportamento default abbastanza adeguato e non riguardano SPID in senso stretto.

Ho aggiunto una descrizione più umana, appendendola alla originale

````
Il fornitore di servizi deve garantire che le asserzioni non vengano ripresentate, mantenendo il set di identificatori di richiesta (``ID``) usati come per le ``<AuthnRequest>`` per tutta la durata di tempo per cui l'asserzione risulta essere valida, secondo l'attributo ``NotOnOrAfter`` dell'elemento ``<SubjectConfirmationData>`` presente nell'asserzione stessa. Più semplicemente un SP deve esclusivamente accettare Response riconducibili a Richieste di Autenticazione già inoltrate e non scadute, Response non sollecitate da precedenti AuthnRequest devono essere pertanto scartate.
````
