### ISSUE TITLE
Refuso nelle specifiche dell'elemento AttributeQuery

### ISSUE THREAD

**Issue by alranel** [italia/spid-regole-tecniche#22]
Nel paragrafo 2.2.2.1 che specifica i contenuti dell'elemento `<AttributeQuery>` è riportato:

> deve essere presente l’elemento `<Signature>` riportante la firma sull’asserzione apposta dall’Identity Provider emittente

Credo ci siano due refusi:

* anziché di "asserzione" si dovrebbe parlare di "richiesta", intendendo la AttributeQuery (che non è un'asserzione)
* anziché dell'Identity Provider la firma dovrebbe essere del Service Provider

**Comment by peppelinux** [comment]
Decisamente SI!
Ready to be committed
