### ISSUE TITLE
Attributo AllowCreate per AuthnRequest/NameIdPolicy

### ISSUE THREAD

**Issue by davidlibrera** [italia/spid-regole-tecniche#25]
Vorrei un chiarimento riguardo a questo

http://spid-regole-tecniche.readthedocs.io/en/latest/regole-tecniche-idp.html#nameidpolicy

La libreria che viene utilizzata su ruby è ruby-saml che in queste righe
https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/authrequest.rb#L124
forza l'attributo ```AllowCreate=true```

ma stando al documento http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf riga 2123, questo parametro è opzionale.

Esistono casi in cui in SPID l'attributo ```AllowCreate``` debba essere omesso?

**Comment by alexrj** [comment]
No. Può essere omesso. Se presente deve necessariamente essere `true`.
(In SPID non esiste il caso in cui `AllowCreate=false`)

**Comment by davidlibrera** [comment]
Ok, perfetto e, per chiarire, ė una cosa che viene stabilita da un service provider a priori o oppure c'è la possibilità che ogni singola richiesta di authn possa variare?
