### ISSUE TITLE
Discrepanza tra regole tecniche pdf e html

### ISSUE THREAD

**Issue by davidlibrera** [italia/spid-regole-tecniche#26]
Ho notato una discrepanza tra il pdf (https://www.agid.gov.it/sites/default/files/repository_files/circolari/spid-regole_tecniche_v1.pdf) e la versione html (http://spid-regole-tecniche.readthedocs.io/en/latest/regole-tecniche-idp.html).

In particolare la sezione su ```RequestedAuthnContext```, dove in base al pdf le classi ammesse sono ```urn:oasis:names:tc:SAML:2.0:ac:classes:SpidL1``` mentre in base alla versione html ```https://www.spid.gov.it/SpidL1```

Questa discrepanza è strettamente connessa con https://github.com/italia/spid-testenv2/issues/49

**Comment by davidlibrera** [comment]
Nella versione PDF non è menzionata la sezione SingleLogoutService,  sia per quanto riguarda i Service Provider che per gli Identity Provider

**Comment by alexrj** [comment]
@davidlibrera la documentazione HTML è un work in progress, è totalmente incompleta e quindi va ignorata, c'è del lavoro in corso.

Questa issue è un duplicato di #16 quindi la chiudo.

Su `RequestedAuthnContext` attenzione: l'avviso n. 5 emenda il PDF delle Regole Tecniche, quindi è corretto il valore `https://www.spid.gov.it/SpidL1 `.
