### ISSUE TITLE
Gestione centralizzata?

### ISSUE THREAD

**Issue by giampiero7** [italia/spid-regole-tecniche#3]
Non sono sicuro questo sia il posto giusto per discuterne, ma tentar non nuoce ;)
Come mai non è stata pensata una gestione centralizzata delle richieste di identificazione SPID?Invece di richiedere all'utente di selezionare il proprio provider, non sarebbe meglio che le richieste venissero gestite centralmente e, eventualmente, smistate ai vari provider dal servizio centrale?
Grazie!

**Comment by madduci** [comment]
@giampiero7 beh se fosse centralizzata, si avrebbe un single point of failure, mentre con piú provider si hanno regole e flessibilitá differenti. Ad esempio, in Germania, Estonia e Olanda ci si affida proprio alla decentralizzazione del servizio, dove ogni service provider viene gestito da organizzazioni differenti.
Quello che dovrebbe esser invece centralizzato é invece proprio lo SPID (e.g. carta di identitá digitale, come la nPA tedesca - eID)

**Comment by umbros** [comment]
Corretto quello che dice Madduci. Sicuramente a livello di esperienza utente sarebbe stata forse migliore. Altro aspetto il fatto che un utente può avere più identità SPID o meglio più identità su diversi IdP. Per il resto ti segnalo che è in fase di sviluppo un nuovo pulsante spid che non prevederà più il dropdown. Per le prossime segnalazioni o argomenti ti invito ad utilizzare e frequentare il forum di developers https://forum.developers.italia.it.

**Comment by giampiero7** [comment]
Ciao ragazzi,
Grazie per le vostre risposte!
Come suggerito da @umbros, ho spostato la discussione sul forum:
https://forum.developers.italia.it/t/gestione-centralizzata/189

Vi aspetto ;)

**Comment by umbros** [comment]
ottimo @giampiero7 grazie
