### ISSUE TITLE
Esempio AuthnRequest - Posizione Signature

### ISSUE THREAD

**Issue by lorenzocattaneo** [italia/spid-regole-tecniche#30]
Nell'esempio di AuthnRequest l'elemento Signature è posizionato per primo, immediatamente dopo la radice, mentre dovrebbe trovarsi dopo l'elemento Issuer.

[https://spid-regole-tecniche.readthedocs.io/en/latest/regole-tecniche-idp.html#esempio-di-authnrequest](https://spid-regole-tecniche.readthedocs.io/en/latest/regole-tecniche-idp.html#esempio-di-authnrequest)

**Comment by alranel** [comment]
Grazie @lorenzocattaneo, questa cosa è stata risolta.
