### ISSUE TITLE
spid-regole-tecniche2 non esiste su readthedocs

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-regole-tecniche#31]
https://spid-regole-tecniche2.readthedocs.io/  riporta "Page Not Found",
questo link è riportato qui:
https://github.com/italia/spid-regole-tecniche/blame/master/README.md#L9

**Comment by alranel** [comment]
Grazie! Ho corretto il link:
https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/
