### ISSUE TITLE
Error autentication Spid Poste ID. Code Level II

### ISSUE THREAD

**Issue by marcodadamo** [italia/spid-regole-tecniche#35]
With **SPID POSTE** ID during authentication I enter the user name, password I click on login, From the moment I receive the **SMS** with the code and I insert it in the text field the message login failed appears. The message appears every time I try to authenticate.

**Comment by peppelinux** [comment]
Hi @marcodadamo,
I think that this kind of issue should be faced with the assistance of the SP technicians or, in worst case, by POSTE ID helpdesk. 
Considering that POSTE ID is working quite fine nowadays, for the most of the SPs, I think that your problem should be investaiged with the SP help desk.

best regards
