### ISSUE TITLE
Generazione certificati da aggiornare

### ISSUE THREAD

**Issue by Martini991** [italia/spid-regole-tecniche#39]
C'è una discrepanza tra quello che c'è scritto nella sezione di generazione certificati e quello che è riportato nell'avviso 29v3, in particolare manca la parte dell'uri:
```
uri (OID 2.5.4.83) — EntityID del SP, così come riportato nell’attributo entityID del tag XML
<EntityDescriptor> del metadata del SP.
```

Se possibile aggiungerei anche un riferimento agli script ufficiali in cima, in modo da semplificare il lavoro a chi si trova per la prima volta ad affrontare il problema: `https://github.com/italia/spid-compliant-certificates`

- Sezione da aggiornare: https://docs.italia.it/italia/spid/spid-regole-tecniche/it/34.1.2/metadata.html#certificati
- Avviso 29: https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n29v3-specifiche_sp_pubblici_e_privati_0.pdf

**Comment by peppelinux** [comment]
Grazie Lorenzo,

risolti qui:
https://github.com/italia/spid-regole-tecniche/commit/9400e26b613840dcbcdf04cbf0c4e8da89a120e3

a breve seguirà una nuova release
