### ISSUE TITLE
Richiesta aiuto regole tecniche e validazione Attributi SAML

### ISSUE THREAD

**Issue by andrewkrgeo** [italia/spid-regole-tecniche#43]
Salve a tutti,

Stiamo implementando un service provider e un servizio che valida/trasforma le informazioni provenienti dall’identity provider.

Nel SAML Assertion restituito dal provider di identita Infocert (individuato per puro caso facendo un test di login) abbiamo riscontrato la seguente “condizione” che sembra violare la seguente regola tecnica:

`un elemento di tipo relativo ad un attributo certificato dovrà comprendere: - l’attributo Name attualizzato con identificativi di attributo definiti nella tabella attributi SPID (cfr. SPID - Tabella attributi); - uno o più elementi ciascuno riportante l’attributo Type (cfr. SPID - Tabella attributi) e attualizzato con il valore assunto dall’attributo;`

(pagina 24 https://www.agid.gov.it/sites/default/files/repository_files/circolari/spid-regole_tecniche_v1.pdf)

Quanto viene ricevuto dal IDP è questo estratto per il campo ivaCode (che sicuramente non è valorizzato):

```
<saml2:Attribute FriendlyName="Partita IVA" Name="ivaCode">
<saml2:AttributeValue xmlns:xs=http://www.w3.org/2001/XMLSchema xmlns:xsi=http://www.w3.org/2001/XMLSchema-instance xsi:type="xs:string"/>
</saml2:Attribute>
```

È corretto che un attributo possa presentare un valore “NULL” e quindi venga restituito l'attributo in quel modo oppure l'IDP non doveva proprio riportare l'attributo?

In altri casi simili (altro IDP) abbiamo visto che il comportamento del servizio è quello di mettere comunque un valore (Es. un trattino ‘-‘) quando il valore non fosse effettivamente disponibile.

Saluti, ci fate capire meglio la regola tecnica in questo caso quale deve essere – per poter implementare, seguendo lo standard, le regole di validazione dei claims?

Grazie mille,

**Comment by peppelinux** [comment]
Dove non specificato nelle regole tecniche spid, entra in gioco SAML Core. In questo caso:
````
If a SAML attribute includes an empty value, such as the empty string, the corresponding  element MUST be empty (generally this is serialized as ). [...] If a SAML attribute includes a "null" value, the corresponding  element MUST be empty and MUST contain the reserved xsi:nil XML attribute with a value of "true" or "1"
````

https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf

Pagina 31, grazie per la condivisione confrontarci fa sempre bene!
