### ISSUE TITLE
Chiarire uso di AssertionConsumerServiceIndex oppure coppia AssertionConsumerServiceURL/ProtocolBinding 

### ISSUE THREAD

**Issue by zer0uno** [italia/spid-regole-tecniche#47]
La documentazione [qui](https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/single-sign-on.html#authnrequest) presente riporta:

> In alternativa all’attributo `AssertionConsumerServiceIndex` (scelta sconsigliata) possono essere presenti: [...] `AssertionConsumerServiceURL` [...] `ProtocolBinding`

la frase è un po' ambigua, non è chiaro se l'essere sconsigliato è relativo a `AssertionConsumerServiceIndex` oppure alla coppia ( `AssertionConsumerServiceURL` ,`ProtocolBinding` ).

In aggiunta non è neanche chiaro se una delle due opzioni `AssertionConsumerServiceIndex` oppure coppia `AssertionConsumerServiceURL/ProtocolBinding` deve obbligatoriamente essere presente, poiché dalla [documentazione](https://www.agid.gov.it/sites/default/files/repository_files/documentazione/spid-avviso-n6-note-sul-dispiegamento-di-spid-presso-i-gestori-di-servizi-v1.pdf) sulla creazione del SP metadata viene esplicitato che è possibile definire un ACS di default:

> _isDefault_ presente in un solo elemento atto ad evidenziare l’indirizzo di risposta nel caso non sia presente nella richiesta (SAMLReq) l’ attributo SAML (AssertionConsumerServiceIndex) previsto per selezionarlo;

**Comment by peppelinux** [comment]
grazie @zer0uno la tua giusta osservazione verrà considerata per il rilascio della prossima versione di spid-regole-tecniche

**Comment by peppelinux** [comment]
Ho rimosso la dicitura ambigua, rianalizzando il tutto posso piuttosto consigliare di poter aggiungere, opzionalmente, ProtocolBinding e AssertionConsumerServiceURL come buona pratica (più flessibile).

Non a caso nell'esempio di una authn request ho prediletto questa soluzione.
grazie @zer0uno per avercelo fatto notare
