### ISSUE TITLE
Quali documenti sono ammessi per richiedere SPID?

### ISSUE THREAD

**Issue by matpag** [italia/spid-regole-tecniche#59]
Nel file `attributi.rst` nel campo `idCard` come documenti identificativi vengono elencati i seguenti possibili valori:

```
cartaIdentita, passaporto, patenteGuida; patenteNautica; librettoPensione, 
patentinoImpTermici, portoArmi, tesseraRiconoscimento
```
[ma nelle FAQ ufficiali](https://helpdesk.spid.gov.it/knowledgebase.php?article=5#:~:text=Per%20richiedere%20e%20ottenere%20le,il%20tesserino%20del%20codice%20fiscale\).) c'é scritto che gli unici documenti ammessi sono Carta di identità, Passaporto e Patente.

Quindi quali sono quelli realmente accettati?

Grazie,
Mattia

**Comment by peppelinux** [comment]
Ciao @matpag 

la documentazione che riporti si riferisce ai documenti richiesti per ottenere spid, mentre nelle regole tecniche si indicano gli attributi SPID rilasciabili da un IDP ad un SP

**Comment by peppelinux** [comment]
Per il  riconsocimento di una persona pe l'approvigionamento di una identità digitale è una procedura diversa da una autenticazione e consenguente rilascio di attributi, dall'identity provider ad un sito web di un fornitore di servizio (SP)

nel primo caso è una procedura amministrativa, nel secondo caso è una procedura tecnica e conforme ad uno standard che è SAML2

in SAML2 negli attributi non torniamo copia autenticata di un documento, ma solo un identificativo di questo. La validità di questi dati è affermata dal livello di garanzia della tua identità digitale, emessa da una parte di fiducia (IDP riconosiuto da AgID)

**Comment by matpag** [comment]
Grazie ad entrambi per le risposte, 
Le motivazioni esposte da Antonio Giovanni in effetti ora mi chiariscono un po' le idee sul perché ci sono in giro SPID che inviano attributi di quel genere.
